# Generated by Django 2.2.3 on 2019-07-10 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgmtApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='encargado',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
    ]
