# Generated by Django 2.2.3 on 2019-07-10 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mgmtApp', '0003_cliente_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamLeader', models.ForeignKey(help_text='Seleccione el lider del Team', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TeamLeader', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ManyToManyField(default='', help_text='Seleccione empleados que conforman este team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
