# Generated by Django 2.2.3 on 2019-07-10 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmtApp', '0004_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='nombre',
            field=models.CharField(default='', help_text='Ingrese el nombre del Team', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamLeader',
            field=models.ForeignKey(help_text='Seleccione el lider del Team', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamLeader', to=settings.AUTH_USER_MODEL),
        ),
    ]
