# Generated by Django 2.2.3 on 2019-07-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmtApp', '0005_auto_20190710_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(help_text='Ingrese la marca del vehiculo', max_length=30)),
                ('modelo', models.CharField(help_text='Ingrese el modelo del vehiculo', max_length=30)),
                ('nroPatente', models.CharField(help_text='Ingrese el numero de chapa del Vehiculo', max_length=6, unique=True)),
                ('fechaMantenimiento', models.DateField(help_text='Ingrese la fecha del ultimo mantenimiento realizado al Vehiculo')),
                ('kmMantenimiento', models.IntegerField(help_text='Ingrese el kilometraje del vehiculo al momento del ultimo mantenimiento')),
                ('kilometraje', models.IntegerField(help_text='Ingrese el kilometraje actual')),
            ],
        ),
    ]
