# Generated by Django 2.2.3 on 2019-07-10 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmtApp', '0009_auto_20190710_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('m', 'Transaccion Madre'), ('a', 'actualizacion')], default='m', help_text='Seleccione tipo de transaccion', max_length=1)),
                ('nroTransaccion', models.IntegerField(blank=True, help_text='Ingrese el numero de transaccion bancaria provehido por el banco', null=True)),
                ('combustible', models.IntegerField(default=0, help_text='Ingrese el monto a transferir para compra de combustible')),
                ('viatico', models.IntegerField(default=0, help_text='Ingrese el monto a transferir para viaticos')),
                ('hospedaje', models.IntegerField(default=0, help_text='Ingrese el monto a transferir para hospedaje')),
                ('peaje', models.IntegerField(default=0, help_text='Ingrese el monto a transferir para peajes')),
                ('imprevistos', models.IntegerField(default=0, help_text='Ingrese el monto a transferir para gastos imprevistos')),
                ('estado', models.CharField(blank=True, choices=[('a', 'Abierta'), ('c', 'Cerrada')], default='a', max_length=1)),
                ('fecha', models.DateField(help_text='Ingrese fecha de realizacion de la transaccion')),
                ('observacion', models.TextField(blank=True, help_text='Observaciones', max_length=1000, null=True)),
                ('tarea', models.ForeignKey(help_text='Seleccione la tarea asociada a la trasaccion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mgmtApp.Tarea')),
            ],
        ),
    ]
