# Generated by Django 2.2.3 on 2019-07-10 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmtApp', '0010_transaccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroComprobante', models.IntegerField(help_text='Ingrese el numero de comprobante')),
                ('monto', models.IntegerField(help_text='Ingrese el monto de la compra en guaranies')),
                ('tipo', models.CharField(choices=[('c', 'Combustible'), ('v', 'Viatico'), ('p', 'Peaje'), ('i', 'Imprevistos'), ('h', 'Hospedaje')], default='c', help_text='Seleccione el tipo de producto adquirido', max_length=1)),
                ('razonSocial', models.CharField(help_text='Ingrese la Razon Social del emisor del comprobante', max_length=30)),
                ('urlComprobante', models.CharField(blank=True, help_text='URL de la imagen almacenada', max_length=200)),
                ('urlKilometraje', models.CharField(blank=True, max_length=200, null=True)),
                ('urlDispenser', models.CharField(blank=True, max_length=200, null=True)),
                ('RUC', models.IntegerField(help_text='Ingrese RUC del emisor del comprobante')),
                ('validado', models.CharField(choices=[('s', 'Si'), ('n', 'No')], default='n', max_length=1)),
                ('observacion', models.TextField(blank=True, max_length=1000, null=True)),
                ('tarea', models.ForeignKey(help_text='Seleccione tarea a la que esta asociada el comprobante', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mgmtApp.Tarea')),
            ],
        ),
    ]
