# Generated by Django 2.2.3 on 2019-07-10 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmtApp', '0011_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('descripcion', models.TextField(help_text='Ingrese una descripcion completa del trabajo realizado', max_length=1000)),
                ('costoCombustible', models.IntegerField(help_text='Ingrese el gasto utilizado en combustible para la ejecucion de la tarea')),
                ('costoPeaje', models.IntegerField(help_text='Ingrese el gasto utilizado en peajes para la ejecucion de la tarea')),
                ('costoImprevistos', models.IntegerField(help_text='Ingrese el gasto utilizado en imprevistos para la ejecucion de la tarea')),
                ('observacion', models.TextField(blank=True, help_text='Observaciones', max_length=1000, null=True)),
                ('tarea', models.ForeignKey(help_text='Seleccione tarea a la que esta asociada el reporte', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mgmtApp.Tarea')),
            ],
        ),
    ]
